module.exports = [

  { value:'ad',   css:"flag ad", label:"Andorra"},
  { value:'ae',   css:"flag ae", label:"United Arab Emirates"},
  { value:'af',   css:"flag af", label:"Afghanistan"},
    { value:'ag',   css:"flag ag", label:"Antigua and Barbuda"},
  { value:'ai',   css:"flag ai", label:"Anguilla"},
    { value:'al',   css:"flag al", label:"Albania"},
    { value:'am',   css:"flag am", label:"Armenia"},
    { value:'an',   css:"flag an", label:"Netherlands Antilles"},
  { value:'ao',   css:"flag ao", label:"Angola"},
    { value:'aq',   css:"flag aq", label:"Antarctica"},
    { value:'ar',   css:"flag ar", label:"Argentina"},
    { value:'as',   css:"flag as", label:"American Samoa"},
  { value:'at',   css:"flag at", label:"Austria"},
    { value:'au',   css:"flag au", label:"Australia"},
    { value:'aw',   css:"flag aw", label:"Aruba"},
    { value:'ax',   css:"flag ax", label:"Aland Islands"},
  { value:'az',   css:"flag az", label:"Azerbaijan"},
    { value:'ba',   css:"flag ba", label:"Bosnia and Herzegovina"},
  { value:'bb',   css:"flag bb", label:"Barbados"},
    { value:'bd',   css:"flag bd", label:"Bangladesh"},
    { value:'be',   css:"flag be", label:"Belgium"},
    { value:'bf',   css:"flag bf", label:"Burkina Faso"},
  { value:'bg',   css:"flag bg", label:"Bulgaria"},
    { value:'bh',   css:"flag bh", label:"Bahrain"},
    { value:'bi',   css:"flag bi", label:"Burundi"},
    { value:'bj',   css:"flag bj", label:"Benin"},
    { value:'bm',   css:"flag bm", label:"Bermuda"},
    { value:'bn',   css:"flag bn", label:"Brunei Darussalam"},
  { value:'bo',   css:"flag bo", label:"Bolivia"},
    { value:'br',   css:"flag br", label:"Brazil"},
    { value:'bs',   css:"flag bs", label:"Bahamas"},
    { value:'bt',   css:"flag bt", label:"Bhutan"},
    { value:'bv',   css:"flag bv", label:"Bouvet Island"},
  { value:'bw',   css:"flag bw", label:"Botswana"},
    { value:'by',   css:"flag by", label:"Belarus"},
    { value:'bz',   css:"flag bz", label:"Belize"},
    { value:'ca',   css:"flag ca", label:"Canada"},
    { value:'cc',   css:"flag cc", label:"Cocos (Keeling) Islands"},
  { value:'cd',   css:"flag cd", label:"Democratic Republic of the Congo"},
  { value:'cf',   css:"flag cf", label:"Central African Republic"},
  { value:'cg',   css:"flag cg", label:"Congo"},
    { value:'ch',   css:"flag ch", label:"Switzerland"},
    { value:'ci',   css:"flag ci", label:"Cote D'Ivoire (Ivory Coast)"},
  { value:'ck',   css:"flag ck", label:"Cook Islands"},
  { value:'cl',   css:"flag cl", label:"Chile"},
    { value:'cm',   css:"flag cm", label:"Cameroon"},
    { value:'cn',   css:"flag cn", label:"China"},
    { value:'co',   css:"flag co", label:"Colombia"},
    { value:'cr',   css:"flag cr", label:"Costa Rica"},
  { value:'cs',   css:"flag cs", label:"Serbia and Montenegro"},
  { value:'cu',   css:"flag cu", label:"Cuba"},
    { value:'cv',   css:"flag cv", label:"Cape Verde"},
  { value:'cx',   css:"flag cx", label:"Christmas Island"},
  { value:'cy',   css:"flag cy", label:"Cyprus"},
    { value:'cz',   css:"flag cz", label:"Czech Republic"},
  { value:'de',   css:"flag de", label:"Germany"},
    { value:'dj',   css:"flag dj", label:"Djibouti"},
    { value:'dk',   css:"flag dk", label:"Denmark"},
    { value:'dm',   css:"flag dm", label:"Dominica"},
    { value:'do',   css:"flag do", label:"Dominican Republic"},
  { value:'dz',   css:"flag dz", label:"Algeria"},
    { value:'ec',   css:"flag ec", label:"Ecuador"},
    { value:'ee',   css:"flag ee", label:"Estonia"},
    { value:'eg',   css:"flag eg", label:"Egypt"},
    { value:'eh',   css:"flag eh", label:"Western Sahara"},
  { value:'er',   css:"flag er", label:"Eritrea"},
    { value:'es',   css:"flag es", label:"Spain"},
    { value:'et',   css:"flag et", label:"Ethiopia"},
    { value:'fi',   css:"flag fi", label:"Finland"},
    { value:'fj',   css:"flag fj", label:"Fiji"},
    { value:'fk',   css:"flag fk", label:"Falkland Islands (Malvinas)"},
  { value:'fm',   css:"flag fm", label:"Federated States of Micronesia"},
  { value:'fo',   css:"flag fo", label:"Faroe Islands"},
  { value:'fr',   css:"flag fr", label:"France"},
    { value:'fx',   css:"flag fx", label:"France, Metropolitan"},
  { value:'ga',   css:"flag ga", label:"Gabon"},
    { value:'gb',   css:"flag gb", label:"Great Britain (UK)"},
  { value:'gd',   css:"flag gd", label:"Grenada"},
    { value:'ge',   css:"flag ge", label:"Georgia"},
    { value:'gf',   css:"flag gf", label:"French Guiana"},
  { value:'gh',   css:"flag gh", label:"Ghana"},
    { value:'gi',   css:"flag gi", label:"Gibraltar"},
    { value:'gl',   css:"flag gl", label:"Greenland"},
    { value:'gm',   css:"flag gm", label:"Gambia"},
    { value:'gn',   css:"flag gn", label:"Guinea"},
    { value:'gp',   css:"flag gp", label:"Guadeloupe"},
    { value:'gq',   css:"flag gq", label:"Equatorial Guinea"},
  { value:'gr',   css:"flag gr", label:"Greece"},
    { value:'gs',   css:"flag gs", label:"S. Georgia and S. Sandwich Islands"},
  { value:'gt',   css:"flag gt", label:"Guatemala"},
    { value:'gu',   css:"flag gu", label:"Guam"},
    { value:'gw',   css:"flag gw", label:"Guinea-Bissau"},
    { value:'gy',   css:"flag gy", label:"Guyana"},
    { value:'hk',   css:"flag hk", label:"Hong Kong"},
  { value:'hm',   css:"flag hm", label:"Heard Island and McDonald Islands"},
  { value:'hn',   css:"flag hn", label:"Honduras"},
    { value:'hr',   css:"flag hr", label:"Croatia (Hrvatska)"},
    { value:'ht',   css:"flag ht", label:"Haiti"},
    { value:'hu',   css:"flag hu", label:"Hungary"},
    { value:'id',   css:"flag id", label:"Indonesia"},
    { value:'ie',   css:"flag ie", label:"Ireland"},
    { value:'il',   css:"flag il", label:"Israel"},
    { value:'in',   css:"flag in", label:"India"},
    { value:'io',   css:"flag io", label:"British Indian Ocean Territory"},
  { value:'iq',   css:"flag iq", label:"Iraq"},
    { value:'ir',   css:"flag ir", label:"Iran"},
    { value:'is',   css:"flag is", label:"Iceland"},
    { value:'it',   css:"flag it", label:"Italy"},
    { value:'jm',   css:"flag jm", label:"Jamaica"},
    { value:'jo',   css:"flag jo", label:"Jordan"},
    { value:'jp',   css:"flag jp", label:"Japan"},
    { value:'ke',   css:"flag ke", label:"Kenya"},
    { value:'kg',   css:"flag kg", label:"Kyrgyzstan"},
    { value:'kh',   css:"flag kh", label:"Cambodia"},
    { value:'ki',   css:"flag ki", label:"Kiribati"},
    { value:'km',   css:"flag km", label:"Comoros"},
    { value:'kn',   css:"flag kn", label:"Saint Kitts and Nevis"},
  { value:'kp',   css:"flag kp", label:"Korea (North)"},
    { value:'kr',   css:"flag kr", label:"Korea (South)"},
    { value:'kw',   css:"flag kw", label:"Kuwait"},
    { value:'ky',   css:"flag ky", label:"Cayman Islands"},
  { value:'kz',   css:"flag kz", label:"Kazakhstan"},
    { value:'la',   css:"flag la", label:"Laos"},
    { value:'lb',   css:"flag lb", label:"Lebanon"},
    { value:'lc',   css:"flag lc", label:"Saint Lucia"},
  { value:'li',   css:"flag li", label:"Liechtenstein"},
    { value:'lk',   css:"flag lk", label:"Sri Lanka"},
  { value:'lr',   css:"flag lr", label:"Liberia"},
    { value:'ls',   css:"flag ls", label:"Lesotho"},
    { value:'lt',   css:"flag lt", label:"Lithuania"},
    { value:'lu',   css:"flag lu", label:"Luxembourg"},
    { value:'lv',   css:"flag lv", label:"Latvia"},
    { value:'ly',   css:"flag ly", label:"Libya"},
    { value:'ma',   css:"flag ma", label:"Morocco"},
    { value:'mc',   css:"flag mc", label:"Monaco"},
    { value:'md',   css:"flag md", label:"Moldova"},
    { value:'mg',   css:"flag mg", label:"Madagascar"},
    { value:'mh',   css:"flag mh", label:"Marshall Islands"},
  { value:'mk',   css:"flag mk", label:"Macedonia"},
    { value:'ml',   css:"flag ml", label:"Mali"},
    { value:'mm',   css:"flag mm", label:"Myanmar"},
    { value:'mn',   css:"flag mn", label:"Mongolia"},
    { value:'mo',   css:"flag mo", label:"Macao"},
    { value:'mp',   css:"flag mp", label:"Northern Mariana Islands"},
  { value:'mq',   css:"flag mq", label:"Martinique"},
    { value:'mr',   css:"flag mr", label:"Mauritania"},
    { value:'ms',   css:"flag ms", label:"Montserrat"},
    { value:'mt',   css:"flag mt", label:"Malta"},
    { value:'mu',   css:"flag mu", label:"Mauritius"},
    { value:'mv',   css:"flag mv", label:"Maldives"},
    { value:'mw',   css:"flag mw", label:"Malawi"},
    { value:'mx',   css:"flag mx", label:"Mexico"},
    { value:'my',   css:"flag my", label:"Malaysia"},
    { value:'mz',   css:"flag mz", label:"Mozambique"},
    { value:'na',   css:"flag na", label:"Namibia"},
    { value:'nc',   css:"flag nc", label:"New Caledonia"},
  { value:'ne',   css:"flag ne", label:"Niger"},
    { value:'nf',   css:"flag nf", label:"Norfolk Island"},
  { value:'ng',   css:"flag ng", label:"Nigeria"},
    { value:'ni',   css:"flag ni", label:"Nicaragua"},
    { value:'nl',   css:"flag nl", label:"Netherlands"},
    { value:'no',   css:"flag no", label:"Norway"},
    { value:'np',   css:"flag np", label:"Nepal"},
    { value:'nr',   css:"flag nr", label:"Nauru"},
    { value:'nu',   css:"flag nu", label:"Niue"},
    { value:'nz',   css:"flag nz", label:"New Zealand (Aotearoa)"},
  { value:'om',   css:"flag om", label:"Oman"},
    { value:'pa',   css:"flag pa", label:"Panama"},
    { value:'pe',   css:"flag pe", label:"Peru"},
    { value:'pf',   css:"flag pf", label:"French Polynesia"},
  { value:'pg',   css:"flag pg", label:"Papua New Guinea"},
  { value:'ph',   css:"flag ph", label:"Philippines"},
    { value:'pk',   css:"flag pk", label:"Pakistan"},
    { value:'pl',   css:"flag pl", label:"Poland"},
    { value:'pm',   css:"flag pm", label:"Saint Pierre and Miquelon"},
  { value:'pn',   css:"flag pn", label:"Pitcairn"},
    { value:'pr',   css:"flag pr", label:"Puerto Rico"},
  { value:'ps',   css:"flag ps", label:"Palestinian Territory"},
  { value:'pt',   css:"flag pt", label:"Portugal"},
    { value:'pw',   css:"flag pw", label:"Palau"},
    { value:'py',   css:"flag py", label:"Paraguay"},
    { value:'qa',   css:"flag qa", label:"Qatar"},
    { value:'re',   css:"flag re", label:"Reunion"},
    { value:'ro',   css:"flag ro", label:"Romania"},
    { value:'ru',   css:"flag ru", label:"Russian Federation"},
  { value:'rw',   css:"flag rw", label:"Rwanda"},
    { value:'sa',   css:"flag sa", label:"Saudi Arabia"},
  { value:'sb',   css:"flag sb", label:"Solomon Islands"},
  { value:'sc',   css:"flag sc", label:"Seychelles"},
    { value:'sd',   css:"flag sd", label:"Sudan"},
    { value:'se',   css:"flag se", label:"Sweden"},
    { value:'sg',   css:"flag sg", label:"Singapore"},
    { value:'sh',   css:"flag sh", label:"Saint Helena"},
  { value:'si',   css:"flag si", label:"Slovenia"},
    { value:'sj',   css:"flag sj", label:"Svalbard and Jan Mayen"},
  { value:'sk',   css:"flag sk", label:"Slovakia"},
    { value:'sl',   css:"flag sl", label:"Sierra Leone"},
  { value:'sm',   css:"flag sm", label:"San Marino"},
  { value:'sn',   css:"flag sn", label:"Senegal"},
    { value:'so',   css:"flag so", label:"Somalia"},
    { value:'sr',   css:"flag sr", label:"Suriname"},
    { value:'st',   css:"flag st", label:"Sao Tome and Principe"},
  { value:'su',   css:"flag su", label:"USSR (former)"},
    { value:'sv',   css:"flag sv", label:"El Salvador"},
  { value:'sy',   css:"flag sy", label:"Syria"},
    { value:'sz',   css:"flag sz", label:"Swaziland"},
    { value:'tc',   css:"flag tc", label:"Turks and Caicos Islands"},
  { value:'td',   css:"flag td", label:"Chad"},
    { value:'tf',   css:"flag tf", label:"French Southern Territories"},
  { value:'tg',   css:"flag tg", label:"Togo"},
    { value:'th',   css:"flag th", label:"Thailand"},
    { value:'tj',   css:"flag tj", label:"Tajikistan"},
    { value:'tk',   css:"flag tk", label:"Tokelau"},
    { value:'tl',   css:"flag tl", label:"Timor-Leste"},
    { value:'tm',   css:"flag tm", label:"Turkmenistan"},
    { value:'tn',   css:"flag tn", label:"Tunisia"},
    { value:'to',   css:"flag to", label:"Tonga"},
    { value:'tp',   css:"flag tp", label:"East Timor"},
  { value:'tr',   css:"flag tr", label:"Turkey"},
    { value:'tt',   css:"flag tt", label:"Trinidad and Tobago"},
  { value:'tv',   css:"flag tv", label:"Tuvalu"},
    { value:'tw',   css:"flag tw", label:"Taiwan"},
    { value:'tz',   css:"flag tz", label:"Tanzania"},
    { value:'ua',   css:"flag ua", label:"Ukraine"},
    { value:'ug',   css:"flag ug", label:"Uganda"},
    { value:'uk',   css:"flag uk", label:"United Kingdom"},
  { value:'um',   css:"flag um", label:"United States Minor Outlying Islands"},
  { value:'us',   css:"flag us", label:"United States"},
  { value:'uy',   css:"flag uy", label:"Uruguay"},
    { value:'uz',   css:"flag uz", label:"Uzbekistan"},
    { value:'va',   css:"flag va", label:"Vatican City State (Holy See)"},
{ value:'vc',   css:"flag vc", label:"Saint Vincent and the Grenadines"},
{ value:'ve',   css:"flag ve", label:"Venezuela"},
  { value:'vg',   css:"flag vg", label:"Virgin Islands (British)"},
{ value:'vi',   css:"flag vi", label:"Virgin Islands (U.S.)"},
{ value:'vn',   css:"flag vn", label:"Viet Nam"},
{ value:'vu',   css:"flag vu", label:"Vanuatu"},
  { value:'wf',   css:"flag wf", label:"Wallis and Futuna"},
{ value:'ws',   css:"flag ws", label:"Samoa"},
  { value:'ye',   css:"flag ye", label:"Yemen"},
  { value:'yt',   css:"flag yt", label:"Mayotte"},
  { value:'yu',   css:"flag yu", label:"Yugoslavia (former)"},
  { value:'za',   css:"flag za", label:"South Africa"},
{ value:'zm',   css:"flag zm", label:"Zambia"},
  { value:'zr',   css:"flag zr", label:"Zaire (former)"},
  { value:'zw',   css:"flag zw", label:"Zimbabwe"},
];
